Added: New cpp Files
programming-kkw/cpp-important-programs pull request #2
Opened 2023-04-05 16:19 UTC by harshalself

I added some cpp files and included my name is contributers.md

2023-04-05 22:21 UTC, inclinedadarsh commented
Open different pull requests for each file

2023-04-05 22:23 UTC, inclinedadarsh requested changes

2023-04-05 22:23 UTC, inclinedadarsh commented on Addition.cpp
> +// NAME : HARSHAL PATIL
Remove this line

2023-04-05 22:23 UTC, inclinedadarsh commented on Area_Perimeter_Rectangle.cpp
> +// NAME : HARSHAL PATIL
Remove this line

2023-04-05 22:23 UTC, inclinedadarsh commented on Positive_Negative.cpp
> +// NAME : HARSHAL PATIL
Remove this line

2023-04-05 22:23 UTC, inclinedadarsh commented on Quotient_Remainder.cpp
> +// NAME : HARSHAL PATIL
Remove this line

2023-04-05 22:23 UTC, inclinedadarsh commented on Simple_Intrest.cpp
> +// NAME : HARSHAL PATIL
Remove this line

2023-04-07 16:56 UTC, harshalself commented
> 

how to do that "different pull request for each file"

2023-04-09 10:22 UTC, pranavvp16 commented
@harshalself commit with changes in all the file on your forked branch and then Make a pull request

2023-04-09 11:52 UTC, harshalself commented
@pranavvp16 i have made those changed in cppcontribute branch .

2023-04-09 18:54 UTC, harshalself commented
Hello @inclinedadarsh I have done all changes . Please let me know if there are any remaining. Thank You

2023-04-11 18:14 UTC, inclinedadarsh commented
@harshalself after some discussion, we have decided that one person should be able to add only one program so everyone gets an opportunity to make a open-source contribution.

I am going to have to close this PR. You can make a new PR with just one new program.

Also, this programs are really beginner friendly, and are not much complex and this repo is for somewhat complex programs. So please add some complex program from next time. To know more about contributing to the repository, you can check out the [CONTRIBUTING.md](https://github.com/programming-kkw/cpp-important-programs/blob/main/CONTRIBUTING.md) file.

Thank You!

2023-04-11 18:14 UTC, closed without merging

2023-04-11 18:17 UTC, harshalself commented
Yeah sure